
key_secret: 'd1787df1af0db4f79b883a73262239cf'
faucet_key_secret: 'd16003f7364b0546bfd364543e22872c9f139d0447ffc5a4508c113ca49a145e'
annas_fake_password: 'annae123'
sarahs_fake_password: 'david123'
davids_fake_password: 'david123'
johns_fake_password: 'johns123'

AWS_ACCESS_KEY_ID: 'AKIAIF6RQPH6AOFYPAMQ'
AWS_SECRET_ACCESS_KEY: '4WlxfqyyD5DeenNolDRf4qJR3hF6crCjnhJgWCXv'
S3_BUCKET_NAME: 'winestem-assets'