# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
key_secret: 'd1787df1af0db4f79b883a73262239cf'
faucet_key_secret: 'd16003f7364b0546bfd364543e22872c9f139d0447ffc5a4508c113ca49a145e'
annas_fake_password: 'annae123'
sarahs_fake_password: 'david123'
davids_fake_password: 'david123'
johns_fake_password: 'johns123'
# AWSAccessKeyId: 'AKIAJLZTSNXYZYAZ7L5A'
# AWSSecretKey: 'WmY1pWL3TbWZ0++taAXkDiItIJu1Hg7k/CylHWrU'
AWS_ACCESS_KEY_ID: 'AKIAI5OMCDAIXJYF5TFQ'
AWS_SECRET_ACCESS_KEY: '6dsWY0VlGUUt4by4miwjB5hpe79aDWNHPNnbhUC5'
S3_BUCKET_NAME: 'winestem-assets'